### ISSUE TITLE
ImagePreprocessor.py 수정

### ISSUE THREAD

**Issue by suppressor6** [GarlicCook/library_repo#10]
ImagePreprocessor.py 파일에서 5가지 기능을 굳이 class로 묶을 필요는 없을것 같습니다. 오히려 더 복잡해질것 같네요.

**Comment by GarlicCook** [comment]
저도 생각해보니 그런 것 같아서 패키지로 할지 생각 중인데 다른 생각 있으신가요?

**Comment by suppressor6** [comment]
굳이 패키지로 할 필요는 없을것 같고 그냥 클래스만 풀면 될것같아요.

**Comment by GarlicCook** [comment]
클래스만 풀면 그냥 5개의 파일로 하자는 말씀이세요?

**Comment by GarlicCook** [comment]
수정 했습니다.
