### ISSUE TITLE
의견 수렴

### ISSUE THREAD

**Issue by GarlicCook** [GarlicCook/library_repo#21]
기능 branch를 제외하고 단순 수정을 위해 pr한 간이 branch들은 pr후 삭제할까 생각 중인데 여러분들의 생각은 어떠신가요?

**Comment by suppressor6** [comment]
굳이 삭제할필요는 없을것 같습니다

**Comment by GarlicCook** [comment]
> 굳이 삭제할필요는 없을것 같습니다

branch가 10개가 넘어갈텐데 너무 지저분하지 않을까요?

**Comment by suppressor6** [comment]
생각해보니 이제 따로 코드를 수정하거나 추가할일은  없을것같으니 삭제해도 좋을것같네요
