### ISSUE TITLE
얼굴 추출

### ISSUE THREAD

**Issue by jaesung05** [GarlicCook/library_repo#3]
사진속 사람의 얼굴을 사각형으로 잡아내는 기능

**Comment by GarlicCook** [comment]
image_path가 ./library_repo/sample_image/... 으로 돼 있으면 다른 사용자 컴퓨터에서는 사진이 안 불러져서 ./sample_image/... 로 고쳐야 할 것 같습니다.

**Comment by jaesung05** [comment]
close#3
