### ISSUE TITLE
이미지 메타데이터 관리

### ISSUE THREAD

**Issue by suppressor6** [GarlicCook/library_repo#4]
이미지에 저장된 메타데이터 삭제 및 수정하는 기능

**Comment by GarlicCook** [comment]
메타데이터가 위치데이터나 색상을 의미하는건가요?
만약 맞다면 메타데이터가 사라진 부분은 어떻게 되는건가요?

**Comment by suppressor6** [comment]
위치데이터와 찍은 카메라 정보, 촬영일시 등의 내용들을 의미하며 삭제해도 이미지 자체에는 변화가 없는 부가적인 정보들입니다.

**Comment by GarlicCook** [comment]
> 위치데이터와 찍은 카메라 정보, 촬영일시 등의 내용들을 의미하며 삭제해도 이미지 자체에는 변화가 없는 부가적인 정보들입니다.

알겠습니다!
